server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: movies-service
          uri: lb://movies-service/
          predicates:
            - Path=/movie/**
          filters:
            - RewritePath=/movie/(?<segment>.*), /$\{segment}
        - id: cinema-service
          uri: lb://cinema-service/
          predicates:
            - Path=/cinema/**
          filters:
            - RewritePath=/cinema/(?<segment>.*), /$\{segment}
        - id: payment-service
          uri: lb://payment-service/
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /$\{segment}

